import { describe, expect, it } from "vitest";
import { bundledContent } from "../content";
import { buildPublicPackages } from "./publicPackages";
import { CourseRegistry } from "./registry";
import { completeAuthoredActivity, createCourseRuntimeContext, deterministicInstructorFallback, enrollCourse, loadCourseProgress, saveCourseProgress } from "./runtime";
import { parseCoursePackage, serializeCoursePackage, validateCoursePackage } from "./packageValidation";
import type { CoursePackageDocument } from "./packageTypes";

const packages = buildPublicPackages(bundledContent);
const aPlus = packages.find(item => item.manifest.courseId === "a-plus") as CoursePackageDocument;
function clone<T>(value: T): T { return structuredClone(value); }

describe("canonical authored course package", () => {
  it("validates every built-in public package", () => { expect(packages).toHaveLength(3); packages.forEach(document => expect(validateCoursePackage(document).errors).toEqual([])); });
  it("rejects duplicate package IDs and unsupported format versions", () => { const registry = new CourseRegistry(packages, undefined); expect(registry.install(clone(aPlus)).errors.join(" ")).toContain("already provided"); const unsupported = clone(aPlus); unsupported.manifest.formatVersion = 99 as 1; expect(validateCoursePackage(unsupported).errors.join(" ")).toContain("unsupported"); });
  it("rejects mismatched and broken authored references", () => {
    const mismatch = clone(aPlus); mismatch.course.id = "other-course"; expect(validateCoursePackage(mismatch).errors.join(" ")).toContain("match manifest.courseId");
    const brokenLecture = clone(aPlus); const firstModule = brokenLecture.course.modules[0]; brokenLecture.lectures = { courseId: brokenLecture.course.id, version: "1.0.0", explicitLectureIds: ["lecture"], lectures: [{ id: "lecture", title: "Lecture", version: "1.0.0", courseId: brokenLecture.course.id, moduleId: firstModule.id, lessonIds: ["missing-lesson"], abstract: "Lecture", objectives: [], prerequisiteConceptIds: [], estimatedMinutes: 1, references: [], tags: [], explicit: true, segments: [] }] }; expect(validateCoursePackage(brokenLecture).errors.join(" ")).toContain("unknown lesson");
    const unknownActivity = clone(aPlus); (unknownActivity.course.modules[0].lessons[0].activities[0] as unknown as Record<string, unknown>).type = "future"; expect(validateCoursePackage(unknownActivity).errors.join(" ")).toContain("type is unknown");
  });
  it("rejects executable, path, secret, and oversized package fields", () => { const executable = clone(aPlus) as CoursePackageDocument & { command?: string }; executable.command = "powershell -Command whoami"; expect(validateCoursePackage(executable).errors.join(" ")).toContain("not allowed"); const secret = clone(aPlus) as CoursePackageDocument & { metadata?: { apiKey: string } }; secret.metadata = { apiKey: "sk-123456789012345678901234" }; expect(validateCoursePackage(secret).errors.join(" ")).toContain("secret-shaped"); const oversized = clone(aPlus); oversized.course.description = "x".repeat(2_000_001); expect(validateCoursePackage(oversized).errors.join(" ")).toContain("exceeds"); });
  it("serializes deterministically and round-trips the same authored bytes", () => { const first = serializeCoursePackage(aPlus); expect(first).toBe(serializeCoursePackage(clone(aPlus))); const parsed = parseCoursePackage(first); expect(parsed.report.errors).toEqual([]); expect(parsed.document?.course).toEqual(aPlus.course); });
  it("reports unsupported capabilities without executing them", () => { const future = clone(aPlus); future.manifest.packageId = "example.future"; future.manifest.courseId = "example-future"; future.course.id = "example-future"; future.manifest.capabilities = ["network-simulation"]; const result = new CourseRegistry(packages, undefined).install(future); expect(result.installed).toBe(false); expect(result.unsupportedCapabilities).toEqual(["network-simulation"]); });
});

describe("generic runtime and registry", () => {
  it("installs, updates, exports, and removes a local package", () => { const changes: string[] = []; const registry = new CourseRegistry(packages, undefined, change => changes.push(`${change.action}:${change.packageId}`)); const imported = clone(aPlus); imported.manifest.packageId = "local.example.course"; imported.manifest.packageVersion = "1.1.0"; imported.manifest.courseId = "local-example-course"; imported.course.id = "local-example-course"; imported.manifest.visibilityMetadata = { audience: "local" }; const installed = registry.install(imported); expect(installed.installed).toBe(true); const update = clone(imported); update.manifest.packageVersion = "1.2.0"; update.manifest.title = "Updated Local Course"; expect(registry.install(update)).toMatchObject({ installed: true, updated: true }); expect(registry.export("local.example.course")).toContain("local.example.course"); expect(registry.remove("local.example.course", true)).toEqual({ removed: true, archivedProgress: true }); expect(changes).toEqual(["install:local.example.course", "update:local.example.course", "remove:local.example.course"]); });
  it("keeps progress isolated by package/course namespace", () => { const first = createCourseRuntimeContext(aPlus); const second = createCourseRuntimeContext(packages.find(item => item.manifest.courseId === "network-plus")!); const firstProgress = enrollCourse({}, first)[first.progressNamespace]; const secondProgress = enrollCourse({}, second)[second.progressNamespace]; expect(first.progressNamespace).not.toBe(second.progressNamespace); const location = firstProgress.current; const advanced = completeAuthoredActivity(first, firstProgress, location); expect(advanced.lessonProgress[location.lessonId].completedActivityIds).toContain(location.activityId); expect(secondProgress.completedLessonIds).toEqual([]); });
  it("uses provider-neutral deterministic instructor fallback", () => { const response = deterministicInstructorFallback(createCourseRuntimeContext(aPlus), "TEACH", "What should I review?"); expect(response.basis).toBe("fallback"); expect(response.canChangeProgress).toBe(false); expect(response.message).not.toContain("private"); });
  it("does not collide with the legacy learner state storage key", () => { const storage = new Map<string, string>(); const adapter = { getItem: (key: string) => storage.get(key) ?? null, setItem: (key: string, value: string) => storage.set(key, value) } as unknown as Storage; saveCourseProgress({}, adapter); expect(storage.has("skillforge-course-progress-v1")).toBe(true); expect(storage.has("apex-state")).toBe(false); expect(loadCourseProgress(adapter)).toEqual({}); });
});
